#!/bin/sh
set -euf

##
# ImageMagick processesor: resize an image to fill a cover size.
#
# Syntax:
#
#     imagemagick-convert-resize-cover <size> <gravity> <input> <output>
#
# Example:
#
#     imagemagick-convert-resize-cover 80x80 center input.jpg output.jpg
##

program_command="imagemagick-convert-resize-cover"
program_version="1.0.0"
program_created="2022-04-21T15:37:48Z"
program_updated="2022-04-21T15:37:48Z"
program_license="BSD or MIT or GPL"
program_contact="Joel Parker Henderson (joel@joelparkerhenderson.com)"
program_variant="$program_command version $program_version updated $program_updated"

size="$1"
gravity="$2"
src_file_name="$3"
dst_file_name="$4"

convert \
-resize "$size^" \
-extent "$size" \
-gravity "$gravity" \
"$src_file_name" \
"$dst_file_name"
